---
title: "Kharinaev Homework 13.09.2021"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document:
    df_print: paged
---


### Dataset description
  Dataset contains info about stocks of S&P 500 companies (date, open, high, low, close prices, volume, company name (ticker))

### 1.1 Matrix
```{r}
matrix1 <- matrix(rnorm(25), nrow=5)
rownames(matrix1) <- c("x0","x1","x2","x3","x4")
colnames(matrix1) <- c("y0","y1","y2","y3","y4")
matrix1
```
### 1.2 Row and column names
```{r}
rownames(matrix1)
colnames(matrix1)
```
### 1.3 Transpose
```{r}
t(matrix1)
```

### 2.1 Matrix of vectors
```{r}
c1 <- c(1,2,3,4)
c2 <- c(1,2,3,4)
c3 <- c(1,2,3,4)
c4 <- c(1,2,3,4)
matrix2 <- cbind(c1,c2,c3,c4)
rownames(matrix2) <- c("r1","r2","r3","r4")
matrix2
```
### 2.2 It's dimension
```{r}
dim(matrix2)
```

### 3. Check element [2,2]
```{r}
is.numeric(matrix2[2,2])
is.logical(matrix2[2,2])
is.null(matrix2[2,2])
is.nan(matrix2[2,2])
```

### 4. Read CSV and make table
```{r}
data <- read.csv(file = '..\\dataset.csv')
head(data)
```
```{r}
list_data <- list(Date=data[1:100,"date"], Open=data[1:100,"open"], 
                  Close=data[1:100,"close"], Name=data[1:100,"Name"])
list_data$Date[1:5]
list_data$Open[1:5]
list_data$Close[1:5]
list_data$Name[1:5]
```

```{r}
table <- data[1:100,c('date','open','close','Name')]
head(table)
```
### 5.1 Plot and histogram for list
```{r}
plot(list_data$Open, list_data$Close)
```
```{r}
hist(list_data$Open)
```

### 5.2 Plot and histogram for table
```{r}
plot(table[,2],table[,3])
```
```{r}
hist(table[,2])
```

### 6. if-else + for, while, repeat
```{r}
ans <- TRUE
for (i in 1:100){
  if (table[i,"open"] == 0){
    ans <- FALSE
  }
}
if (ans == FALSE){
  print("there are some 0")
} else {
  print("all values is not 0")
}
```
```{r}
ans <- TRUE
i <- 1
while (i<=100){
  if (list_data$Close[i] < 19){
    ans <- FALSE
  }
  i <- i+1
}
if (ans == FALSE){
  print("there are some values below 19")
} else {
  print("all values is above 19")
}
```
```{r}
ans <- TRUE
i <- 1
repeat {
  if (list_data$Close[i] < 10 | list_data$Close[i] > 20){
    ans <- FALSE
    break
  }
  i <- i + 1
  if (i == 100){
    break
  }
}
if (ans == FALSE){
  print("there are some values out of [10,20]")
} else {
  print("all values is in [10,20]")
}
```



